version: '3.3'

services:
  ros:
    image: ros:melodic-ros-base
    container_name: ros
    tty: true
    command: [ "roscore", "-p", "11311" ]
    networks:
      - rosnet
    environment:
      ROS_MASTER_URI: "${ROS_MASTER_URI}"
      ROS_HOSTNAME: "${ROS_HOSTNAME}"
      ROS_DISTRO: "${ROS_DISTRO}"
      CATKIN_PACKAGE_SHARE_DESTINATION: "${CATKIN_PACKAGE_SHARE_DESTINATION}"

  aiorospy-example:
    build: ros-python3
    image: ros-python3
    container_name: aiorospy
    volumes:
      - ./aiorospy_example:/aiorospy_example
    working_dir: /aiorospy_example
    environment:
      ROS_MASTER_URI: "${ROS_MASTER_URI}"
      ROS_HOSTNAME: "${ROS_HOSTNAME}"
      ROS_DISTRO: "${ROS_DISTRO}"
    command: [ "make" ]
    depends_on:
      - ros
    networks:
      - rosnet

networks:
  rosnet:
