main:
		cd /aiorospy_example/ && \
	  /catkin_ws/catkin_virtualenv/catkin_virtualenv/scripts/build_venv \
		  --python-version "3.7" \
	    --requirements /aiorospy_example/aiorospy/requirements.txt

	#python3.7 -u -m pip install -r requirements.txt
	#python3.7 -u --version
	#python3.7 -u actions.py
	#python3.7 -u services.py
